* Config/Preamble :noexport:
** LaTeX Config
:PROPERTIES:
:VISIBILITY: folded
:END:
#+NAME: init
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
(setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))
(add-to-list 'org-latex-classes
             '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

% Change the page layout if you need to
\\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

% Use roboto and lato for fonts
\\renewcommand{\\familydefault}{\\sfdefault}

% Change the colours if you want to
\\definecolor{SlateGrey}{HTML}{2E2E2E}
\\definecolor{LightGrey}{HTML}{666666}
\\definecolor{DarkPastelRed}{HTML}{450808}
\\definecolor{PastelRed}{HTML}{8F0D0D}
\\definecolor{GoldenEarth}{HTML}{E7D192}
\\colorlet{name}{black}
\\colorlet{tagline}{PastelRed}
\\colorlet{heading}{DarkPastelRed}
\\colorlet{headingrule}{GoldenEarth}
\\colorlet{subheading}{PastelRed}
\\colorlet{accent}{PastelRed}
\\colorlet{emphasis}{SlateGrey}
\\colorlet{body}{LightGrey}

% Change some fonts, if necessary
\\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
\\renewcommand{\\personalinfofont}{\\footnotesize}
\\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
\\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

% Change the bullets for itemize and rating marker
% for \cvskill if you want to
\\renewcommand{\\itemmarker}{{\\small\\textbullet}}
\\renewcommand{\\ratingmarker}{\\faCircle}
"

               ("\\cvsection{%s}" . "\\cvsection*{%s}")
               ("\\cvevent{%s}" . "\\cvevent*{%s}")))
(setq org-latex-packages-alist 'nil)
(setq org-latex-default-packages-alist
      '(("rm" "roboto"  t)
        ("defaultsans" "lato" t)
        ("" "paracol" t)
        ))
#+END_SRC
#+LATEX_CLASS: altacv
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.

** Exporter Settings
#+AUTHOR: Sergio Liberman Bronfman
#+EXPORT_FILE_NAME: ./curriculum-vitae.pdf
#+OPTIONS: toc:nil title:nil H:1
** Macros
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: cvskill \cvskill{$1}{$2}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage
* CV Header :ignore:
** Photo & Tagline :ignore:
#+begin_export latex
\name{Sergio Liberman Bronfman}
\tagline{Ingeniero en Machine Learning \& Ingeniero de Datos}
#+end_export

** Personal Info :ignore:
#+begin_export latex
\personalinfo{
  %\homepage{www.aidanscannell.com}
  \email{sergiolib@gmail.com}
  \phone{+46 73 9254482}
  \location{Santiago, Chile}
  \github{sergiolib}
  \linkedin{sergio-liberman-bronfman}
  %\dob{25 September 1990}
  %\driving{Swedish & Chilean driving license}
}
\makecvheader
#+end_export

* CV Column 1 :ignore:
#+begin_export latex
\begin{paracol}{2}
#+end_export
** Empleos recientes
*** Substorm                                                         :ignore:

{{{cvevent(Desarrollador Senior de Machine Learning, Substorm, Ene 2021 - Actualidad, Estocolmo\, Suecia)}}}

- Consultoría en áreas de desarrollo de aplicaciones con Machine Learning, Ingeniería de Datos, ML Ops, y desarrollo de software
- Principal responsable de infrastructura en la nube.
- Desarrollador de pipelines CI/CD tales como scheduling de tareas, unit/integration testing, containerización de servicios, y sistemas multi-entorno para proyectos y servicios
- Líder técnico en proyectos internos y externos
- Desarrollador principal y mantenedor de múltiples servicios y productos utilizados por clientes
- Tutor de estudiantes de tésis y practicantes
- Acenso a Senior en nov 2023

{{{cvtag(Machine Learning)}}}
{{{cvtag(Data Engineering)}}}
{{{cvtag(ML/DevOps)}}}
\medskip
\newline

*** Tésis                                                         :ignore:

{{{cvevent(Projecto de tésis y práctica profesional, Elekta, 2020, Estocolmo\, Suecia)}}}

- Predicción parcial de dósis en cálculos de dósis utilizando Generative Adversarial Networks condicionales
- Modelos de Machine learning generativo diseñados para transformaciones de imágenes y acondicionados para calcular dósis de radioterapia más eficientemente que métodos tradicionales
# - Geometric transformations for efficient prediction of radiotherapy dose (examples: voxel modeling, projections, prediction of residuals, single/multiple beams superposition)

{{{cvtag(CGANs)}}}
{{{cvtag(PyTorch)}}}
{{{cvtag(I+D)}}}
\medskip
\newline

*** ALGES :ignore:

{{{cvevent(Ingeniero de investigación y desarrollo, Advanced Laboratory for Geostatistical Supercomputing (ALGES), Jul 2014 - Ago 2018, Santiago\, Chile)}}}

- Principal desarrollador de múltiples proyectos con financiamiento estatal parcial o total relacionados a estimación de variables geometalúrgicas utilizando imágenes hiper espectrales
- Desarrollo de algoritmos de segmentación espacial y visual, adquisición de imágenes de bandejas de testigos de minería, algoritmos de unmixing hiper espectral, y desarrollo de detección mejorada de cristales con sensores más económicos usando técnicas de machine learning[fn:1]
- Desarrollo de software de exploración con funciones de etiquetado rápido para integrar conocimiento experto a modelos
- Participación en el desarrollo de U-Fo, software desarrollado en ALGES para estimación geometalúrgica. Desarrollo de algoritmo de unfolding (ISOMAP)
  - Acenso a full time en 2016

{{{cvtag(Computer Vision)}}}
{{{cvtag(Embedded programming)}}}
{{{cvtag(Machine Learning)}}}

** Newpage :ignore:
{{{new-page}}}

** Principales proyectos
*** Smart meters                                                     :ignore:
{{{cvevent(Smart Meters, IsMobile)}}}

- Assessed and evaluated image ML model built for optical character recognition from electric meters using mobile phones
- Improved portability of the model by optimizing smaller backbone without impacting performance

{{{cvtag(Python)}}}
{{{cvtag(Tensorflow)}}}
# {{{cvtag(Optimal control)}}}

\medskip

*** NoBias                                                           :ignore:

{{{cvevent(NoBias, Research/Internal)}}}

- Developed a system for removing gender bias of text, provide gender neutral suggestions and educate user to improve writing with less gender bias
- Initial solution used transformers and word embeddings. The newer prototypes use large language models such as GPT-4 and Llama 2
- The project was co-developed with Luleå Tekniska Universitetet with the support of Vinnova
- A demo is available[fn:2]
{{{cvtag(APIs)}}}
{{{cvtag(AWS)}}}
{{{cvtag(Python)}}}
{{{cvtag(Svelte)}}}

\medskip

*** Resource optimization :ignore:noexport:
{{{cvevent(Developer and tech lead Resource Optimization, Internal)}}}

- Developed proof of concept to create an optimal schedule of consultancy resources using convex optimization
  
{{{cvtag(Python)}}}
{{{cvtag(Google Compute Engine)}}}

\medskip

*** Cucumbers                                                        :ignore:
{{{cvevent(Circular product development, Research/internal)}}}

- Industial collaboration project funded by Vinnova to reduce pesticides use and detect early problems in plantations
- Creted image classification and object detetion model for detecting mold, insects and other illnesses in cucumber greenhouse plantations
- Developed an acquistion app for mobile phones to gather data directly from experts in greenhouses of Skåne
  
{{{cvtag(AWS Amplify)}}}
{{{cvtag(Classification)}}}
{{{cvtag(Object detection)}}}
{{{cvtag(Python)}}}

\medskip

*** Max Burgers                                                      :ignore:
{{{cvevent(Data Engineer for analytics team, Max Burgers)}}}

- Development of data source connectors for data ingestion software

{{{cvtag(C\#)}}}
{{{cvtag(Python)}}}
{{{cvtag(REST/SOAP APIs)}}}
{{{cvtag(SQL)}}}

\medskip

*** Telia :ignore:
{{{cvevent(Data Engineer for Revenue Assurance PoC, Telia)}}}

- Developed proof of concept for quantifying leakage of revenue across network and billing layers within Telia’s platforms
- Estimation of leakage was up to 1%. Diagnosed Telia’s income could increase just by avoiding wrong invoices to consumers
- Collaboration with team of analysts from revenue assuarance team, data analysts and data engineers from Telia

{{{cvtag(Scala/Spark)}}}
{{{cvtag(Hive)}}}
{{{cvtag(Airflow)}}}
{{{cvtag(SQL)}}}

\medskip
* CV Column 2 :ignore:
# Switch to the right column - will automatically move to the next page.
#+begin_export latex
\switchcolumn
#+end_export

** Habilidades
{{{cvskill(AWS, 5)}}}
{{{cvskill(Azure, 5)}}}
{{{cvskill(Backend development, 5)}}}
{{{cvskill(C\#, 5)}}}
{{{cvskill(Emacs/Elisp, 5)}}}
{{{cvskill(Git, 5)}}}
{{{cvskill(Python, 5)}}}
{{{cvskill(PyTorch, 5)}}}
{{{cvskill(Scikit Learn, 5)}}}
{{{cvskill(SQL, 5)}}}
{{{cvskill(Terraform, 5)}}}
{{{cvskill(C/C++, 4)}}}
{{{cvskill(OpenCV, 4)}}}
{{{cvskill(Rust, 4)}}}
{{{cvskill(Scala/Spark, 4)}}}
{{{cvskill(Tensorflow/Keras, 4)}}}
{{{cvskill(Typescript, 4)}}}
\smallskip

** Acerca de mi
- Desarrollador de aplicaciones y sistemas complejos de Machine Learning e Ingeniero de Datos extremadamente técnico, versátil, profesional y flexible.

- Ingeniero Eléctrico de la Universidad de Chile especializado en procesamiento de señales e inteligencia computacional. Graduado de máster en Machine Learning de la Real Academia de Tecnología KTH, Estocolmo.

- Mi principal motivación es generar soluciones de datos que tengan un impacto positivo en las rutinas de las personas.

- Disfruto de trabajar en ambientes multidiciplinarios y tengo experiencia en ambientes de trabajo Agile.

- Soy responsable, respetuoso, serio y dedicado. Siempre apunto a aprender algo nuevo y a mejorar mis habilidades.

- Mis fortalezas son la capacidad de proveer de buenas ideas a mi equipo, la alta calidad de mi trabajo a través del cual busco la excelencia, y el entusiasmo en general que plasmo en mis acciones diarias.

- Soy nacido en Santiago de Chile en septiembre de 1990 y vivo en Estocolmo desde agosto de 2018. Pretendo volver a Chile en cuanto consiga una posición permanente allí.

- Mis pasatiempos incluyen viajar, natación, trotar, lectura, ver series o películas, y mantenerme al día con los últimos desarrollos tecnológicos.

** Newpage :ignore: 
{{{new-page}}}

** Educación
*** KTH :ignore:
{{{cvevent(MSc. Machine Learning, Kungliga Tekniska Högskolan, 2020 - 2022, Stockholm\, Sweden)}}}
*** UChile :ignore:
{{{cvevent(BSc. and professional title in Electrical Engineering, University of Chile, 2009 - 2016, Santiago\, Chile)}}}

** Logros
{{{cvachievement(\faCertificate, Udemy, Certificate in Scala/Spark)}}}

{{{divider}}}

{{{cvachievement(\faTrophy, Excellence scholarship laureate, Becas Chile 2019 en Áreas prioritarias.)}}}

{{{divider}}}

{{{cvachievement(\faTrophy,KTH Hattrick award, Awarded to students with A’s in every programming assignment in Artificial
Intelligence course.)}}}

{{{divider}}}

{{{cvachievement(\faTrophy, University of Chile maximal distinction, Graduated from University of Chile with the highest grades.)}}}

{{{divider}}}

{{{cvachievement(\faTrophy, Alumnos destacados, 2013 and 2014 among the best students in Electrical Engineering at University of Chile)}}}

\smallskip

** Lenguajes

{{{cvskill(Spanish (native), 5)}}}

{{{cvskill(English (professional), 5)}}}

{{{cvskill(Swedish (A2), 2)}}}

\smallskip

** Referencias
- Referees provided on request
  
* Back Matter :ignore:
#+begin_export latex
\end{paracol}
\end{document}
#+end_export

* Footnotes
[fn:2] Latest version is live in [[https://dev.nobias.se][https://dev.nobias.se]]

[fn:1] Para más información en nuestro paper: Egaña, Á.F.; Santibáñez-Leal, F.A.; Vidal, C.; Díaz, G.; Liberman, S.; Ehrenfeld, A. A Robust Stochastic Approach to Mineral Hyperspectral Analysis for Geometallurgy. Minerals 2020, 10, 1139. [[https://doi.org/10.3390/min10121139][https://doi.org/10.3390/min10121139]]


* Run code                                                         :noexport:

# Local Variables:
# eval: (org-sbe "init")
# End:
