* Config/Preamble :noexport:
** LaTeX Config
:PROPERTIES:
:VISIBILITY: folded
:END:
#+NAME: init
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
(setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))
(add-to-list 'org-latex-classes
             '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

% Change the page layout if you need to
\\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

% Use roboto and lato for fonts
\\renewcommand{\\familydefault}{\\sfdefault}

% Change the colours if you want to
\\definecolor{SlateGrey}{HTML}{2E2E2E}
\\definecolor{LightGrey}{HTML}{666666}
\\definecolor{DarkPastelRed}{HTML}{450808}
\\definecolor{PastelRed}{HTML}{8F0D0D}
\\definecolor{GoldenEarth}{HTML}{E7D192}
\\colorlet{name}{black}
\\colorlet{tagline}{PastelRed}
\\colorlet{heading}{DarkPastelRed}
\\colorlet{headingrule}{GoldenEarth}
\\colorlet{subheading}{PastelRed}
\\colorlet{accent}{PastelRed}
\\colorlet{emphasis}{SlateGrey}
\\colorlet{body}{LightGrey}

% Change some fonts, if necessary
\\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
\\renewcommand{\\personalinfofont}{\\footnotesize}
\\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
\\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

% Change the bullets for itemize and rating marker
% for \cvskill if you want to
\\renewcommand{\\itemmarker}{{\\small\\textbullet}}
\\renewcommand{\\ratingmarker}{\\faCircle}
"

               ("\\cvsection{%s}" . "\\cvsection*{%s}")
               ("\\cvevent{%s}" . "\\cvevent*{%s}")))
(setq org-latex-packages-alist 'nil)
(setq org-latex-default-packages-alist
      '(("rm" "roboto"  t)
        ("defaultsans" "lato" t)
        ("" "paracol" t)
        ))
#+END_SRC
#+LATEX_CLASS: altacv
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.

** Exporter Settings
#+AUTHOR: Sergio Liberman Bronfman
#+EXPORT_FILE_NAME: ./curriculum-vitae.pdf
#+OPTIONS: toc:nil title:nil H:1
** Macros
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: cvskill \cvskill{$1}{$2}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage
* CV Header :ignore:
** Photo & Tagline :ignore:
#+begin_export latex
\name{Sergio Liberman Bronfman}
\tagline{Ingeniero en Machine Learning \& Ingeniero de Datos}
#+end_export

** Personal Info :ignore:
#+begin_export latex
\personalinfo{
  %\homepage{www.aidanscannell.com}
  \email{sergiolib@gmail.com}
  \phone{+46 73 9254482}
  \location{Santiago, Chile}
  \github{sergiolib}
  \linkedin{sergio-liberman-bronfman}
  %\dob{25 September 1990}
  %\driving{Swedish & Chilean driving license}
}
\makecvheader
#+end_export

* CV Column 1 :ignore:
#+begin_export latex
\begin{paracol}{2}
#+end_export
** Empleos recientes
*** Substorm                                                         :ignore:

{{{cvevent(Desarrollador Senior de Machine Learning, Substorm, Ene 2021 - 2024, Estocolmo\, Suecia)}}}

- Consultoría en áreas de desarrollo de aplicaciones con Machine Learning, Ingeniería de Datos, ML Ops, y desarrollo de software
- Principal responsable de infrastructura en la nube.
- Desarrollador de pipelines CI/CD tales como scheduling de tareas, unit/integration testing, containerización de servicios, y multi-entornos para proyectos
- Desarrollador y mantenedor de múltiples servicios y productos utilizados por clientes
- Tutor de estudiantes de tésis y practicantes
- Ascenso a Senior en noviembre de 2023

{{{cvtag(Machine Learning)}}}
{{{cvtag(Ingeniería de datos)}}}
{{{cvtag(MLOps/DevOps)}}}
{{{cvtag(Liderazgo)}}}
{{{cvtag(Consultoría)}}}
{{{cvtag(Desarrollo de productos)}}}
\medskip
\newline

*** Tésis                                                         :ignore:

{{{cvevent(Proyecto de tésis y práctica profesional, Elekta, 2020, Estocolmo\, Suecia)}}}

- Predicción parcial de cálculo de dósis para radioterapias utilizando Generative Adversarial Networks condicionales
- Modelos de Machine learning generativo diseñados para transformaciones de imágenes y acondicionados para calcular dósis de radioterapia más eficientemente que métodos tradicionales [fn:3]
# - Geometric transformations for efficient prediction of radiotherapy dose (examples: voxel modeling, projections, prediction of residuals, single/multiple beams superposition)

{{{cvtag(CGANs)}}}
{{{cvtag(PyTorch)}}}
{{{cvtag(I+D)}}}
\medskip
\newline

*** ALGES :ignore:

{{{cvevent(Ingeniero de investigación y desarrollo, Advanced Laboratory for Geostatistical Supercomputing (ALGES), Jul 2014 - Ago 2018, Santiago\, Chile)}}}

- Principal desarrollador de múltiples proyectos con financiamiento estatal parcial o total relacionados a estimación de variables geometalúrgicas utilizando imágenes hiper espectrales
- Desarrollo de algoritmos de segmentación espacial y visual, adquisición de imágenes de bandejas de testigos de minería, algoritmos de unmixing hiper espectral [fn:4], y desarrollo de detección mejorada de cristales con sensores más económicos usando técnicas de machine learning[fn:1]
- Desarrollo de software de exploración con funciones de etiquetado rápido para integrar conocimiento experto a modelos
- Participación en el desarrollo de U-Fo, software desarrollado en ALGES para estimación geometalúrgica. Desarrollo de algoritmo de unfolding (ISOMAP)
  - Ascenso a full time en 2016

{{{cvtag(Computer Vision)}}}
{{{cvtag(Programación embebida)}}}
{{{cvtag(Machine Learning)}}}

** Proyectos principales
*** Smart meters                                                     :ignore:
{{{cvevent(Smart Meters, IsMobile)}}}

- Asesoría y evaluación de modelo ML para reconocimiento óptico de dígitos en medidores eléctricos usando smart phones
- Optimización e incremento de portabilidad del modelo principal

{{{cvtag(Python)}}}
{{{cvtag(Tensorflow)}}}
# {{{cvtag(Optimal control)}}}

\medskip

*** NoBias                                                           :ignore:

{{{cvevent(NoBias, Investigación)}}}

- Desarrollo de sistema para remover sesgo de género en textos, entregando sugerencias de texto género-neutrales y educando al usuario a escribir de insesgadamente
- Solución inicial usaba transformers y embeddings de palabras. Nuevos prototipos utilizan LLMs tales como GPT-4 y Llama 3
- El proyecto fue co-desarrollado con la Universidad Técnica de Luleå con el auspicio de la agencia de desarrollo e innovación Vinnova
- Un demo está  disponible actualmente[fn:2]
{{{cvtag(REST)}}}
{{{cvtag(AWS)}}}
{{{cvtag(Python)}}}
{{{cvtag(Svelte)}}}

\medskip

*** Optimización de recursos                              :ignore:noexport:
{{{cvevent(Desarrollador y tech lead}}}}

- Desarrollado PoC de optimización de recursos en empresas de consultoría utilizando programación lineal
  
{{{cvtag(Python)}}}
{{{cvtag(Google Compute Engine)}}}

\medskip

*** Desarrollo de producto circular (Pepinos)                     :ignore:
{{{cvevent(Desarrollo de producto circular, Investigación)}}}

- Proyecto de colaboración industrial parcialmente financiado por la agencia de desarrollo e innovación Vinnova para reducir el uso de pesticidas y detectar problemas en plantaciones de forma temprana
- Desarrollo de modelo de clasificación de imágenes y detección de objetos para la tarea de detección de moho en invernaderos de pepinos
- Desarrollo de aplicación para smart phones para la adquisición remota de imágenes por expertos desde invernaderos en Escania 
  
{{{cvtag(AWS Amplify)}}}
{{{cvtag(Clasificación)}}}
{{{cvtag(Detección de objetos)}}}
{{{cvtag(Python)}}}

\medskip

*** Max Burgers                                                      :ignore:
{{{cvevent(Ingeniero de Datos para el equipo de analítica, Max Burgers)}}}

- Desarrollo de conectores para diferentes fuentes de datos en software de ingestión

{{{cvtag(C\#)}}}
{{{cvtag(Python)}}}
{{{cvtag(REST/SOAP)}}}
{{{cvtag(SQL)}}}

\medskip

*** Telia :ignore:
{{{cvevent(PoC ingeniería de datos para Revenue Assurance, Telia)}}}

- Desarrollada prueba de concepto para cuantificar filtramiento (leakage) de ganancias a través de capas de red y cobranza dentro de las plataformas de Telia
- Estimación de filtramiento previa al proyecto estaba sobre el 1% de ganancias totales. Ganancias de Telia  podrían haberse incrementado tras identificación y corrección de cada caso.
- Colaboración con equipo de analistas de Revenue Assurance, analistas de datos e ingenieros de datos de Telia.

{{{cvtag(Scala/Spark)}}}
{{{cvtag(Hive)}}}
{{{cvtag(Airflow)}}}
{{{cvtag(SQL)}}}

\medskip
*** Intelliplan                                                    :ignore:
{{{cvevent(Servicios IA para plataforma de reclutamiento, Intelliplan)}}}

- Desarrollador y tech lead de múltiples servicios para incorporar IA en plataforma SaaS de reclutamiento desarrollada por Intelliplan. Los servicios implementados y roles fueron:
  1. Búsqueda semántica de CVs dada una descripción ú otro CV (Desarrollador principal)
  2. Asistencia en la escritura de publicaciones para búsqueda de roles (Desarrollador principal)
  3. Portal interactivo y customatizado para clientes de la plataforma (Tech lead)
     
{{{cvtag(LLMs)}}}
{{{cvtag(REST)}}}
{{{cvtag(Python)}}}
{{{cvtag(Embeddings)}}}
{{{cvtag(Azure)}}}
{{{cvtag(Terraform)}}}
{{{cvtag(CI/CD)}}}
{{{cvtag(Liderazgo)}}}
\newline

* CV Column 2 :ignore:
# Switch to the right column - will automatically move to the next page.
#+begin_export latex
\switchcolumn
#+end_export

** Habilidades
{{{cvskill(AWS, 5)}}}
{{{cvskill(Azure, 5)}}}
{{{cvskill(Backend development, 5)}}}
{{{cvskill(C\#, 5)}}}
{{{cvskill(Emacs/Elisp, 5)}}}
{{{cvskill(Git, 5)}}}
{{{cvskill(Python, 5)}}}
{{{cvskill(PyTorch, 5)}}}
{{{cvskill(Scikit Learn, 5)}}}
{{{cvskill(SQL, 5)}}}
{{{cvskill(Terraform, 5)}}}
{{{cvskill(C/C++, 4)}}}
{{{cvskill(OpenCV, 4)}}}
{{{cvskill(Rust, 4)}}}
{{{cvskill(Scala/Spark, 4)}}}
{{{cvskill(Tensorflow/Keras, 4)}}}
{{{cvskill(Typescript, 4)}}}
\smallskip

** Acerca de mi
- Desarrollador de aplicaciones y sistemas complejos de Machine Learning e Ingeniero de Datos extremadamente técnico, versátil, profesional y flexible.

- Ingeniero Eléctrico de la Universidad de Chile especializado en procesamiento de señales e inteligencia computacional. Graduado de máster en Machine Learning de la Real Academia de Tecnología KTH, Estocolmo.

- Mi principal motivación es generar soluciones de datos que tengan un impacto positivo en las rutinas de las personas.

- Disfruto de trabajar en ambientes multidiciplinarios y tengo experiencia en ambientes de trabajo Agile.

- Soy responsable, respetuoso, serio y dedicado. Siempre apunto a aprender algo nuevo y a mejorar mis habilidades.

- Mis fortalezas son la capacidad de proveer de buenas ideas a mi equipo, la alta calidad de mi trabajo a través del cual busco la excelencia, y el entusiasmo en general que plasmo en mis acciones diarias.

- Soy nacido en Santiago de Chile en septiembre de 1990.

- Mis pasatiempos incluyen viajar, natación, trotar, lectura, ver series o películas, cocinar, y mantenerme al día con los últimos desarrollos tecnológicos.

** Newpage :ignore: 
{{{new-page}}}

** Educación
*** KTH :ignore:
{{{cvevent(MSc. Machine Learning, Kungliga Tekniska Högskolan, 2020 - 2022, Estocolmo\, Suecia)}}}
*** UChile :ignore:
{{{cvevent(Ingeniería Eléctrica, Universidad de Chile, 2009 - 2016, Santiago\, Chile)}}}
*** Colegio Craighouse                                            :ignore:
{{{cvevent(Educación Básica y Media, Colegio Craighouse, 1994 - 2008, Santiago\, Chile)}}}

** Logros
{{{cvachievement(\faCertificate, Udemy, Certificado en Scala/Spark)}}}

{{{divider}}}

{{{cvachievement(\faTrophy, Beca de exelencia, Becas Chile 2019 en Áreas prioritarias.)}}}

{{{divider}}}

{{{cvachievement(\faTrophy,Premio KTH Hattrick, Reconocimiento para estudiantes con la nota máxima en cada tarea de programación del curso de Inteligencia Artificial.)}}}

{{{divider}}}

{{{cvachievement(\faTrophy, Distinción máxima Universidad de Chile, Graduado de la U. de Chile con nota final 6.3.)}}}

{{{divider}}}

{{{cvachievement(\faTrophy, Alumno destacado, Dentro de los mejores estudiantes de Ing. Eléctrica en 2013 y 2014)}}}

\smallskip

** Lenguajes

{{{cvskill(Español (nativo), 5)}}}

{{{cvskill(Inglés (profesional), 5)}}}

{{{cvskill(Sueco (A2), 2)}}}

\smallskip

** Referencias
- Referencias serán entregadas ante solicitud del reclutador
  
* Back Matter :ignore:
#+begin_export latex
\end{paracol}
\end{document}
#+end_export

* Footnotes
[fn:4] Liberman Bronfman, S. F. (2016). Técnicas de aplicaciones de separación de señales aplicadas en imágenes hiper espectrales.
[fn:3] Liberman Bronfman, S. F. (2021). 3D Dose Prediction from Partial Dose Calculations using Convolutional Deep Learning models (Dissertation). Recuperado de https://urn.kb.se/resolve?urn=urn:nbn:se:kth:diva-305903
[fn:2] Latest version is live in [[https://dev.nobias.se][https://dev.nobias.se]]

[fn:1] Para más información en nuestro paper: Egaña, Á.F.; Santibáñez-Leal, F.A.; Vidal, C.; Díaz, G.; Liberman, S.; Ehrenfeld, A. A Robust Stochastic Approach to Mineral Hyperspectral Analysis for Geometallurgy. Minerals 2020, 10, 1139. [[https://doi.org/10.3390/min10121139][https://doi.org/10.3390/min10121139]]


* Run code                                                         :noexport:

# Local Variables:
# eval: (org-sbe "init")
# End:
